name: caddy-fmt
on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/caddy-fmt.yml
      - caddy/Dockerfile
      - caddy/Caddyfile
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  caddy-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: caddy-fmt
        run: |
          diff=$(docker run --rm -v ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro caddy:2.11.4@sha256:df7f1c2fb114453b951de51a98efc010db1655a92c2e86be6706714e2417a78d caddy fmt --diff /etc/caddy/Caddyfile)
          if [ -n "$diff" ]; then printf '%s\n' "$diff"; exit 1; fi
