name: lint-and-format
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
defaults:
  run:
    shell: bash
jobs:
  lint-and-format:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11.22.0
      - name: backend
        run: |
          cd backend
          pnpm install --frozen-lockfile
          pnpm biome ci --reporter=default --reporter=github
          node validate-schema.js
          pnpm test
      - name: frontend
        run: |
          cd frontend
          pnpm install --frozen-lockfile
          pnpm biome ci --reporter=default --reporter=github
          ./translations/sort-locale.sh
          pnpm test
          pnpm vite build
      - name: diff
        run: git diff --exit-code
